### ISSUE TITLE
git push -u origin master not working with HTTPS version. Password authentication replaced by token

### ISSUE THREAD

**Issue by MainakRepositor** [MainakRepositor/Git-steps#1]
Recently I found out about the above problem while I was going to push my code to the master branch. (It is applicable for all branches).
The solution is here:

The new GitHub rules require the user to generate a personal GitHub token.

i. To do that, go to the top right corner of the GitHub page where your icon is displayed.

ii. Click on **Settings**

iii. In the left channel that appears in the Settings page, navigate below to **Developer Settings**

iv. Click on the third option from the left pane that says, **"Personal Access Token"**

v.  Click on **Generate new token**

vi. Click on the required checkboxes. If you are having any confusion to choose them, better select all of them.

vii. Provide a name to the token in the text box provided at the top of this section, which has **Note** written on top of it.

viii. Choose an expiry date from the dropdown (you may select never expire if you don't want to create a new token every time)

ix. Copy the token so generated and keep it safe. (Recommended to make multiple copies so that you don't lose it. If you still lose you will have to make a new token).

x. Now make a repo and follow all the previous steps till this step "git commit -m "Your comment" "

xi. After making the commit, just add these lines to the next line in your git bash:

git remote remove origin
git remote add origin https://PERSONALACCESSTOKEN@github.com/USERNAME/REPONAME.git

finally, type git push -u origin <branch name> to make the push successful. 

Hope this will help! :)

**Comment by superbots21** [comment]
Really helped. Thanks!! :)

**Comment by colakar** [comment]
Yes this worked!
